### Get all posts
GET http://127.0.0.1:8000/posts/

### Create a new post
POST http://127.0.0.1:8000/posts/
Content-Type: application/json

{
  "author_name": "Alfred",
  "type": "offer",
  "message": "I can take you there, but I move by 8:00am"
}