### Get all posts
GET http://127.0.0.1:8000/posts/

### Create a new post
POST http://127.0.0.1:8000/posts/
Content-Type: application/json

{
  "author_name": "Lima",
  "type": "offer",
  "message": "I hate you all on this stupid app"
}

### Edit a post
PATCH http://127.0.0.1:8000/posts/bc9ba2f5-7a97-4b2e-b9cb-275d823391fa
Content-Type: application/json

{
  "message": "Please, I need a ride to maitama by 9:00am"
}

### Delete a post
DELETE http://127.0.0.1:8000/posts/d37210fe-bd93-4564-af17-e6239c873692