[project]
name = "api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.119.0",
    "sqlmodel>=0.0.27",
    "uvicorn>=0.37.0",
]
